import { json, db, requireRole, handlerError } from "./_clock.js";
export default async function handler(req,res){
  if(!["GET","POST","PATCH"].includes(req.method))return json(res,405,{error:"Method not allowed"});
  try{requireRole(req,"admin");const client=db();const{data:org,error:oe}=await client.from("organizations").select("id").eq("name","Montes Moreno Healthcare Associates").single();if(oe)throw oe;
    if(req.method==="POST"){const name=String(req.body?.name||"").trim();const code=String(req.body?.code||name).trim().toUpperCase().replace(/[^A-Z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,30);if(name.length<2||!code)return json(res,400,{error:"Enter a valid location name."});const{data:location,error}=await client.from("clinics").insert({organization_id:org.id,name,code,active:true}).select("id,name,code").single();if(error?.code==="23505")return json(res,409,{error:"That location already exists."});if(error)throw error;const{data:admins,error:ae}=await client.from("profiles").select("id").eq("organization_id",org.id).eq("role","admin").eq("active",true);if(ae)throw ae;if(admins?.length){const{error:pe}=await client.from("profile_clinics").upsert(admins.map(admin=>({profile_id:admin.id,clinic_id:location.id})),{onConflict:"profile_id,clinic_id"});if(pe)throw pe;}return json(res,201,{location});}
    if(req.method==="PATCH"){const employeeId=String(req.body?.employeePageId||"");const locationIds=[...new Set((Array.isArray(req.body?.locationIds)?req.body.locationIds:[]).map(String))];if(!employeeId||!locationIds.length)return json(res,400,{error:"Select at least one location."});const[{data:employee,error:ee},{data:valid,error:ve}]=await Promise.all([client.from("employees").select("id").eq("id",employeeId).eq("organization_id",org.id).single(),client.from("clinics").select("id").eq("organization_id",org.id).eq("active",true).in("id",locationIds)]);if(ee||!employee)return json(res,404,{error:"Employee could not be found."});if(ve)throw ve;if((valid||[]).length!==locationIds.length)return json(res,400,{error:"One or more selected locations are invalid."});const{error:de}=await client.from("employee_clinics").delete().eq("employee_id",employeeId);if(de)throw de;const{error:ie}=await client.from("employee_clinics").insert(locationIds.map(clinicId=>({employee_id:employeeId,clinic_id:clinicId})));if(ie)throw ie;return json(res,200,{success:true});}
    const[{data,error},{data:locations,error:le},{data:assignments,error:ae}]=await Promise.all([client.from("employees").select("id,employee_id,full_name,hourly_rate,active,must_change_password,hire_date,notes").order("employee_id"),client.from("clinics").select("id,name,code").eq("organization_id",org.id).eq("active",true).order("name"),client.from("employee_clinics").select("employee_id,clinic_id,clinic:clinics(name)")]);if(error)throw error;if(le)throw le;if(ae)throw ae;const employees=(data||[]).map(x=>{const own=(assignments||[]).filter(a=>a.employee_id===x.id);return{pageId:x.id,id:String(x.employee_id),employeeId:String(x.employee_id),name:x.full_name,employeeName:x.full_name,rate:Number(x.hourly_rate),hourlyRate:Number(x.hourly_rate),active:x.active,mustChangePassword:x.must_change_password,hireDate:x.hire_date,notes:x.notes||"",locationIds:own.map(a=>a.clinic_id),locationNames:own.map(a=>a.clinic?.name).filter(Boolean)}});return json(res,200,{employees,total:employees.length,locations:locations||[]});
  }catch(e){return handlerError(res,e);}
}
